### ISSUE TITLE
REVIEW (Calculadora)

### ISSUE THREAD

**Issue by JohnKun136NVCP** [OscarSuaz/Github_Proteco#1]
https://github.com/OscarSuaz/Github_Proteco/blob/324e6627e943becdfc28c407335a026125b053e9/Calculadora/calculadora.py#L1
La calculadora tiene que ser en C, no en en Python :v.

**Comment by OscarSuaz** [comment]
Ya agregué el archivo  C para la calculadora, no sabía que tenía que ser en C, sorry
